# Generated by Django 5.1.4 on 2024-12-15 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_orderhistorty_cart_remove_cartitem_cart_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileseller',
            name='specialized',
            field=models.CharField(blank=True, choices=[('Engine & Transmission', 'المكينة والقير'), ('Electircal', 'قطع كهربائية'), ('Exterior & Body', 'البودي'), ('lights', 'الأنوار'), ('Cooling & Heating', 'التبريد والتكييف'), ('Interior & Accessories', 'الداخلية والاكسسوارت'), ('Suspensions', 'الميزانية / نظام التعليق'), ('Mechanical', 'قطع ميكانيكية'), ('Uncategorized', 'قطع غير مصنفة'), ('All', 'الكل')], max_length=64, null=True),
        ),
    ]
