# Generated by Django 5.1.2 on 2024-12-16 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_orderhistorty_cart_remove_cartitem_cart_and_more'),
        ('autoparts', '0003_alter_product_part_direction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileseller',
            name='specialized',
        ),
        migrations.AddField(
            model_name='profileseller',
            name='specializaties',
            field=models.ManyToManyField(to='autoparts.category'),
        ),
    ]
