# Generated by Django 5.1.4 on 2024-12-11 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoparts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='alternative_name',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
