# Generated by Django 5.1.2 on 2024-12-12 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoparts', '0002_part_alternative_name_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='part_direction',
            field=models.CharField(blank=True, choices=[('Right', 'يمين'), ('Left', 'يسار')], max_length=64, null=True),
        ),
    ]
