# Generated by Django 5.1.4 on 2024-12-15 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoparts', '0003_alter_product_part_direction'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='delivery_cost',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
