# Generated by Django 5.1.4 on 2024-12-16 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoparts', '0005_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='products_images/', upload_to='products_images/'),
        ),
    ]
