# Generated by Django 5.1.4 on 2024-12-16 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('PENDING', 'انتظار مراجعة البائع'), ('ACCEPTED', 'قيد التوصيل'), ('DELIVERED', 'تم التوصيل'), ('DENIED', 'رفض')], default='PENDING', max_length=20),
        ),
    ]
