# Generated by Django 5.1.4 on 2024-12-16 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_profileseller_specialized_and_more'),
        ('autoparts', '0005_alter_product_image'),
        ('sellers', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(default=22, on_delete=django.db.models.deletion.CASCADE, to='autoparts.product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.profileseller'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('PENDING', 'انتظار مراجعة البائع'), ('ACCEPTED', 'قيد التوصيل'), ('DENIED', 'رفض')], default='PENDING', max_length=20),
        ),
    ]
